/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package patrones;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import patrones.interfaces.Cliente;
/**
 *
 * @author demin
 */
public class Icliente extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    
    private Dba db;
    private Factory fc;
    
    private int id;
    private String nombre;
    private String apellido;
    private String genero;
    private String fecha_nacimiento;
    private String estado_civil;
    
    private int selectrow;
    private int idtemp=0;
    
    public Icliente(Dba dba,Factory fac) {
        initComponents();
        db=dba;
        fc=fac;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        in_nombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        in_apellido = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        in_nacimiento = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        out_Table = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        in_bgenero = new javax.swing.JComboBox<>();
        in_bEestado = new javax.swing.JComboBox<>();
        in_id = new javax.swing.JTextField();
        in_btypeclient = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Eliminar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Cargar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Guardar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Mostrar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre:");

        jLabel2.setText("Apellido:");

        jLabel3.setText("Genero:");

        in_nacimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                in_nacimientoActionPerformed(evt);
            }
        });

        jLabel4.setText("Fecha nacimiento:");

        jLabel5.setText("Estado Civil");

        jLabel6.setText("ID :");

        out_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nombre", "Apellido", "Genero", "Fecha Nacimiento", "Estado civil"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        out_Table.setToolTipText("");
        jScrollPane1.setViewportView(out_Table);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setText("Cliente");

        in_bgenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hombre", "Mujer", "Indefinido" }));

        in_bEestado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Soltero", "Casado", "Union X" }));

        in_btypeclient.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "clienteEstandar", "clientePlatino", "clientePremium" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(in_btypeclient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(in_id, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(in_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(in_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(10, 10, 10)
                                            .addComponent(in_bgenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(in_nacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(26, 26, 26)
                                            .addComponent(in_bEestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(22, 22, 22)
                                            .addComponent(jLabel6)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(167, 167, 167)
                                                    .addComponent(jLabel8))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(174, 174, 174)
                                                    .addComponent(jButton5))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(42, 42, 42)
                                                    .addComponent(jLabel1)
                                                    .addGap(41, 41, 41)
                                                    .addComponent(jLabel2)
                                                    .addGap(44, 44, 44)
                                                    .addComponent(jLabel3)
                                                    .addGap(28, 28, 28)
                                                    .addComponent(jLabel4)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel5))))))
                                .addGap(51, 51, 51)))
                        .addGap(0, 11, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel8)
                .addGap(2, 2, 2)
                .addComponent(in_btypeclient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(in_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(in_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(in_nacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(in_bgenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(in_bEestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(in_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(jButton4)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2))))
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // BOTON AGREGAR
        // clienteEstandar clientePlatino clientePremium  
        String type=in_btypeclient.getSelectedItem().toString();
        id = Integer.valueOf(in_id.getText());
        nombre=in_nombre.getText();
        apellido=in_apellido.getText();
        genero=in_bgenero.getSelectedItem().toString();
        fecha_nacimiento=in_nacimiento.getText();
        estado_civil=in_bEestado.getSelectedItem().toString();
        System.out.println("++++++"+id+" "+nombre+" "+apellido+" "+genero+" "+fecha_nacimiento+" "+estado_civil);
        
        Object [] fila={id,nombre,apellido,genero,fecha_nacimiento,estado_civil};
        add(fila);
        
        Cliente cl=fc.getFabricaCliente().getCliente(type);  
        cl.saludar();
        cl.setId(id);
        cl.setNombre(nombre);
        cl.setApellido(apellido);
        cl.setGenero(genero);
        cl.setFechaNacimiento(fecha_nacimiento);
        cl.setEstadocivil(estado_civil);        
        db.getClienttable().addCliente(cl);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //BOTON ELIMINAR
        id = Integer.valueOf(in_id.getText());
        db.getClienttable().delCliente(id);
        cleartable();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // BOTON CARGAR
        selectrow=out_Table.getSelectedRow();
        Object [] fila=new Object[10];
        if (selectrow>=0) {          
            DefaultTableModel defaultTableModel = (DefaultTableModel) out_Table.getModel();            
            fila=new Object[defaultTableModel.getColumnCount()];  
            for (int i = 0; i < fila.length; i++) {
                fila[i]=defaultTableModel.getValueAt(selectrow, i);
            }
        }
        idtemp=Integer.valueOf(fila[0].toString());
        in_id.setText(fila[0].toString());
        in_nombre.setText(fila[1].toString());
        in_apellido.setText(fila[2].toString());
        in_nacimiento.setText(fila[4].toString());
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // BOTON GUARDAR-CARGA
        String type;
        id = idtemp;
        if (id>=0) {
            type=in_btypeclient.getSelectedItem().toString();
            nombre=in_nombre.getText();
            apellido=in_apellido.getText();
            genero=in_bgenero.getSelectedItem().toString();
            fecha_nacimiento=in_nacimiento.getText();
            estado_civil=in_bEestado.getSelectedItem().toString();

            Cliente cl=fc.getFabricaCliente().getCliente(type);  
            cl.saludar();
            cl.setId(id);
            cl.setNombre(nombre);
            cl.setApellido(apellido);
            cl.setGenero(genero);
            cl.setFechaNacimiento(fecha_nacimiento);
            cl.setEstadocivil(estado_civil);                      
            db.getClienttable().updateCliente(idtemp,cl);
        }
        cleartable();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // BOTON MOSTRAR
        cleartable();        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void in_nacimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_in_nacimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_in_nacimientoActionPerformed
    
    public void add(Object [] fila){
        DefaultTableModel modelo = (DefaultTableModel) out_Table.getModel();
        modelo.addRow(fila);
        out_Table.setModel(modelo);
        in_id.setText("");
        in_nombre.setText("");
        in_apellido.setText("");
        in_nacimiento.setText("");
    }
    
    public void cleartable(){        
        DefaultTableModel defaultTableModel = (DefaultTableModel) out_Table.getModel();
        while ( 0 < out_Table.getRowCount()) {
            defaultTableModel.removeRow(0);
        }
        fill();
    }
    
    public void fill(){
        ArrayList<Cliente> list= db.getClienttable().clientes;
        
        for(Cliente cliente: list){                
            Object [] fila={cliente.getId(),cliente.getNombre(),cliente.getApellido(),cliente.getGenero(),cliente.getFechaNacimiento(),cliente.getEstadocivil()};
            add(fila);
        }
    }
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField in_apellido;
    private javax.swing.JComboBox<String> in_bEestado;
    private javax.swing.JComboBox<String> in_bgenero;
    private javax.swing.JComboBox<String> in_btypeclient;
    private javax.swing.JTextField in_id;
    private javax.swing.JTextField in_nacimiento;
    private javax.swing.JTextField in_nombre;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable out_Table;
    // End of variables declaration//GEN-END:variables
}
