/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package patrones;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import patrones.interfaces.Cliente;
import patrones.interfaces.Factura;
import patrones.interfaces.Item;
/**
 *
 * @author demin
 */
public class Ifactura extends javax.swing.JFrame {

    
    private Dba db;
    private Factory fc;
    
    private int id;
    private String fecha;
    private int numusuario;
    private Cliente Usuario;
    private int totalfactura;
    private String Estado;
    
    private ArrayList<Item> listitems;
    private int selectrow;
    private int idtemp=0;
    
    public Ifactura(Dba dba,Factory fac) {
        initComponents();
        db=dba;
        fc=fac;
        listitems=new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        in_fecha = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        in_cliente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        in_totalfactura = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        out_Table = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        in_bEestado = new javax.swing.JComboBox<>();
        in_id = new javax.swing.JTextField();
        in_btypeclient = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        out_tableitems = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        in_bItems = new javax.swing.JComboBox<>();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Eliminar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Cargar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Guardar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Mostrar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel1.setText("fecha");

        jLabel2.setText("cliente");

        in_totalfactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                in_totalfacturaActionPerformed(evt);
            }
        });

        jLabel4.setText("Total factura");

        jLabel5.setText("Estado");

        jLabel6.setText("Nro factura");

        out_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nr factura", "Fecha", "Cliente", "Total factura", "Estado", "Descripcion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        out_Table.setToolTipText("");
        jScrollPane1.setViewportView(out_Table);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setText("Factura");

        in_bEestado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pagada", "Por Pagar", "Cuota" }));

        in_btypeclient.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "facturaVencida", "facturaPagada", "facturaPromocion" }));

        out_tableitems.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Descripcion", "Valor"
            }
        ));
        jScrollPane2.setViewportView(out_tableitems);

        jButton6.setText("add");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        in_bItems.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Click R" }));
        in_bItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                in_bItemsActionPerformed(evt);
            }
        });

        jButton7.setText("remove");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("R");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1)
                                .addGap(57, 57, 57)
                                .addComponent(jLabel2)
                                .addGap(51, 51, 51)
                                .addComponent(jLabel8))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jButton1)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton2)
                                        .addGap(68, 68, 68))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jButton5)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(in_id, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(in_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(in_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(15, 15, 15)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel5))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(jButton3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton4))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(in_totalfactura, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(in_bEestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(61, 61, 61))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(13, 13, 13)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jButton6)
                        .addGap(18, 18, 18)
                        .addComponent(jButton7)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(in_bItems, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(20, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(in_btypeclient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel8)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(in_btypeclient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5)
                        .addComponent(jLabel6))
                    .addComponent(in_bItems, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(in_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(in_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(in_totalfactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(in_bEestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(in_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(jButton4)
                            .addComponent(jButton2)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton6)
                            .addComponent(jButton7))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // BOTON AGREGAR
        // clienteEstandar clientePlatino clientePremium  
        String type=in_btypeclient.getSelectedItem().toString();
        id = Integer.valueOf(in_id.getText());
        fecha=in_fecha.getText();
        totalfactura=Integer.valueOf(in_totalfactura.getText());
        Estado=in_bEestado.getSelectedItem().toString();
        numusuario=Integer.valueOf(in_cliente.getText());
        searchcliente(numusuario);
        System.out.println("++++++"+id+" "+fecha+" "+Usuario+" "+totalfactura+" "+Estado);
        
        
        Factura cl=fc.getFabricaFactura().getFactura(type);  
        cl.validarEstado();
        cl.setNroFactura(id);
        cl.setFechaFactura(fecha);
        cl.setTotalFactura(Integer.valueOf(totalfactura));
        cl.setEstado(Estado);       
        if (Usuario!=null) {   
            cl.setCliente(Usuario);
            cl.setItems(listitems);
            db.getFacturatable().addFactura(cl);
        }
        cleartable();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //BOTON ELIMINAR
        id = Integer.valueOf(in_id.getText());
        db.getClienttable().delCliente(id);
        cleartable();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // BOTON CARGAR
        selectrow=out_Table.getSelectedRow();
        Object [] fila=new Object[10];
        if (selectrow>=0) {          
            DefaultTableModel defaultTableModel = (DefaultTableModel) out_Table.getModel();            
            fila=new Object[defaultTableModel.getColumnCount()];  
            for (int i = 0; i < fila.length; i++) {
                fila[i]=defaultTableModel.getValueAt(selectrow, i);
            }
        }
        idtemp=Integer.valueOf(fila[0].toString());
        in_id.setText(fila[0].toString());
        in_fecha.setText(fila[1].toString());
        ArrayList<Cliente> list= db.getClienttable().clientes;        
        for(Cliente client: list){                
            if (fila[2].toString().equalsIgnoreCase(client.getNombre())) {
                in_cliente.setText(String.valueOf(client.getId()));
            }
        }
        in_totalfactura.setText(fila[3].toString());
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // BOTON GUARDAR-CARGA
        String type;
        id = idtemp;
        if (id>=0) {
            type=in_btypeclient.getSelectedItem().toString();
            fecha=in_fecha.getText();
            totalfactura=Integer.valueOf(in_totalfactura.getText());
            Estado=in_totalfactura.getText();
            numusuario=Integer.valueOf(in_cliente.getText());
            searchcliente(numusuario);
            
            Factura cl=fc.getFabricaFactura().getFactura(type);  
            cl.validarEstado();
            cl.setNroFactura(id);
            cl.setFechaFactura(fecha);
            cl.setTotalFactura(Integer.valueOf(totalfactura));
            cl.setEstado(Estado);  
            if (Usuario!=null) { 
                cl.setCliente(Usuario);
                cl.setItems(listitems);
                db.getFacturatable().addFactura(cl);
            }
        }
        cleartable();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // BOTON MOSTRAR
        cleartable();        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void in_totalfacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_in_totalfacturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_in_totalfacturaActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        fill_boxitems();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        //BOTON AGREGAR ITEM
        additem();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // 
        //BOTON ELIMINAAR ITEM
        int selecitem=out_tableitems.getSelectedRow();       
        listitems.remove(selecitem);
        fill_items();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void in_bItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_in_bItemsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_in_bItemsActionPerformed
    
    public void add(Object [] fila){
        DefaultTableModel modelo = (DefaultTableModel) out_Table.getModel();
        modelo.addRow(fila);
        out_Table.setModel(modelo);
        in_id.setText("");
        in_fecha.setText("");
        in_cliente.setText("");
        in_totalfactura.setText("");
    }
    
    public void cleartable(){        
        DefaultTableModel defaultTableModel = (DefaultTableModel) out_Table.getModel();
        while ( 0 < out_Table.getRowCount()) {
            defaultTableModel.removeRow(0);
        }
        fill();
    }
    
    public void fill(){
        ArrayList<Factura> list= db.getFacturatable().facturas;
        
        for(Factura factu: list){                
            Object [] fila={factu.getNroFactura(),factu.getFechaFactura(),factu.getCliente().getNombre(),factu.getTotalFactura(),factu.getEstado(),factu.getItems().size()};
            add(fila);
        }
    }
    
    public void fill_boxitems(){
        ArrayList<Item> list= db.getItemtable().items;
        
        in_bItems.removeAllItems();
        for(Item items: list){                
            in_bItems.addItem(items.getDescripcion());
        }
    }
    public void fill_items(){
        DefaultTableModel defaultTableModel = (DefaultTableModel) out_tableitems.getModel();
        while ( 0 < out_tableitems.getRowCount()) {
            defaultTableModel.removeRow(0);
        }
        
        ArrayList<Item> list= db.getItemtable().items;        
        Object [] fila=new Object[2];
        DefaultTableModel modelo = (DefaultTableModel) out_tableitems.getModel();
        
         
        in_bItems.removeAllItems();
        for(Item items: listitems){                
            fila[0]=items.getDescripcion();
            fila[1]=items.getValorUnidad();
            modelo.addRow(fila);
        }
    }
    public void searchcliente(int ida){
        ArrayList<Cliente> list= db.getClienttable().clientes;
        
        for(Cliente client: list){                
            if (ida==client.getId()) {
                Usuario=client;
            }
        }
    }
    
    public void additem(){
        ArrayList<Item> list= db.getItemtable().items;
        Object [] fila=new Object[2];
        DefaultTableModel modelo = (DefaultTableModel) out_tableitems.getModel();
        
        for(Item item: list){                
            if (item.getDescripcion().equalsIgnoreCase(in_bItems.getSelectedItem().toString())) {
                listitems.add(item);
                fila[0]=item.getDescripcion();
                fila[1]=item.getValorUnidad();
                modelo.addRow(fila);
            }
        }
        
    }
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> in_bEestado;
    private javax.swing.JComboBox<String> in_bItems;
    private javax.swing.JComboBox<String> in_btypeclient;
    private javax.swing.JTextField in_cliente;
    private javax.swing.JTextField in_fecha;
    private javax.swing.JTextField in_id;
    private javax.swing.JTextField in_totalfactura;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable out_Table;
    private javax.swing.JTable out_tableitems;
    // End of variables declaration//GEN-END:variables
}
