/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package patrones;
import java.awt.Container;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.table.DefaultTableModel;
import patrones.interfaces.Item;
import patrones.interfaces.TipoItem;
/**
 *
 * @author demin
 */
public class Iitem extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    
    private Dba db;
    private Factory fc;
    
    private int id;
    private String Descripcion;
    private int valor_unidad;
    private TipoItem typeitem;
    private String texttipoitem;
    
    private int selectrow;
    private int idtemp=0;
    
    public Iitem(Dba dba,Factory fac) {
        initComponents();
        db=dba;
        fc=fac;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        in_descripcion = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        in_valorunidad = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        out_Table = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        in_tipoitem = new javax.swing.JComboBox<>();
        in_id = new javax.swing.JTextField();
        in_btypeclient = new javax.swing.JComboBox<>();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Eliminar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Cargar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Guardar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Mostrar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel1.setText("Descripcion");

        jLabel2.setText("Valor unidad");

        jLabel3.setText("Tipo item");

        jLabel6.setText("ID :");

        out_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Tipo item", "Descripcion", "Valor Unidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        out_Table.setToolTipText("");
        jScrollPane1.setViewportView(out_Table);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setText("Item");

        in_tipoitem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Click R" }));
        in_tipoitem.setToolTipText("");

        in_btypeclient.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "itemDelicado", "itemRobusto", "itemEstandar" }));

        jButton6.setText("R");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(in_id, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(in_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(in_valorunidad, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(in_tipoitem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(in_btypeclient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(61, 61, 61)
                                        .addComponent(jButton6))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(110, 110, 110)
                                        .addComponent(jLabel2)
                                        .addGap(31, 31, 31)
                                        .addComponent(jLabel3))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(88, 88, 88)
                                        .addComponent(jLabel8))))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jButton5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(in_btypeclient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(in_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(in_valorunidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(in_tipoitem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(in_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(28, 28, 28)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // BOTON AGREGAR
        // clienteEstandar clientePlatino clientePremium  
        String type=in_btypeclient.getSelectedItem().toString();
        id = Integer.valueOf(in_id.getText());
        Descripcion=in_descripcion.getText();
        valor_unidad=Integer.valueOf(in_valorunidad.getText());
        texttipoitem=in_tipoitem.getSelectedItem().toString();
        typetostring();
        System.out.println("++++++"+id+" "+Descripcion+" "+valor_unidad+" "+texttipoitem);
        
        Item cl=fc.getFabricaItems().getItem(type);  
        cl.consultarRobustes();
        cl.setId(id);
        cl.setDescripcion(Descripcion);
        cl.setValorUnidad(valor_unidad);
        cl.setTipoItem(typeitem);  
        db.getItemtable().addItem(cl);        
        
        cleartable();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //BOTON ELIMINAR
        id = Integer.valueOf(in_id.getText());
        db.getItemtable().delItem(id);
        cleartable();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // BOTON CARGAR
        selectrow=out_Table.getSelectedRow();
        Object [] fila=new Object[10];
        if (selectrow>=0) {          
            DefaultTableModel defaultTableModel = (DefaultTableModel) out_Table.getModel();            
            fila=new Object[defaultTableModel.getColumnCount()];  
            for (int i = 0; i < fila.length; i++) {
                fila[i]=defaultTableModel.getValueAt(selectrow, i);
            }
        }
        idtemp=Integer.valueOf(fila[0].toString());
        in_id.setText(fila[0].toString());
        in_descripcion.setText(fila[2].toString());
        in_valorunidad.setText(fila[3].toString());
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // BOTON GUARDAR-CARGA
        String type;
        id = idtemp;
        if (id>=0) {
            type=in_btypeclient.getSelectedItem().toString();
            Descripcion=in_descripcion.getText();
            valor_unidad=Integer.valueOf(in_valorunidad.getText());
            texttipoitem=in_tipoitem.getSelectedItem().toString();
            
            typetostring();
            
            Item cl=fc.getFabricaItems().getItem(type);  
            cl.consultarRobustes();
            cl.setId(id);
            cl.setDescripcion(Descripcion);
            cl.setValorUnidad(valor_unidad);
            cl.setTipoItem(typeitem);                     
            db.getItemtable().updateItem(idtemp,cl);
        }
        cleartable();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // BOTON MOSTRAR
        cleartable();  
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // Refresh
       ArrayList<TipoItem> list= db.getTipoItemtable().tipoItems; 
        
        in_tipoitem.removeAllItems();
        for(TipoItem tipoitem: list){ 
            in_tipoitem.addItem(tipoitem.getDescripcion());
        }
    }//GEN-LAST:event_jButton6ActionPerformed
    
    public void add(Object [] fila){
        DefaultTableModel modelo = (DefaultTableModel) out_Table.getModel();
        modelo.addRow(fila);
        out_Table.setModel(modelo);
        in_id.setText("");
        in_descripcion.setText("");
        in_valorunidad.setText("");
    }
    
    public void cleartable(){        
        DefaultTableModel defaultTableModel = (DefaultTableModel) out_Table.getModel();
        while ( 0 < out_Table.getRowCount()) {
            defaultTableModel.removeRow(0);
        }
        fill();
    }
    
    public void fill(){
        ArrayList<Item> list= db.getItemtable().items;
        
        for(Item item: list){                
            Object [] fila={item.getId(),item.getTipoItem().getDescripcion(),item.getDescripcion(),item.getValorUnidad()};
            add(fila);
        }
    }
    
    public void typetostring(){
        String val=in_tipoitem.getSelectedItem().toString();
        ArrayList<TipoItem> list= db.getTipoItemtable().tipoItems;
        
        for(TipoItem tipeitem: list){                
            if (tipeitem.getDescripcion().equalsIgnoreCase(val)) {
                typeitem=tipeitem;
            }
        }
    }
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> in_btypeclient;
    private javax.swing.JTextField in_descripcion;
    private javax.swing.JTextField in_id;
    private javax.swing.JComboBox<String> in_tipoitem;
    private javax.swing.JTextField in_valorunidad;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable out_Table;
    // End of variables declaration//GEN-END:variables
}
